language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  CI=true
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm run unit && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
