[package]
name = "pastelogue-neon"
version = "0.1.0"
authors = ["Deseteral <deseteral@gmail.com>"]
edition = "2018"

[lib]
name = "pastelogue_neon"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.3.1"

[dependencies]
neon = "0.3.1"
pastelogue = "0.1.0"
