name: Build

on: [push]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, windows-2019]
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: | # TODO: Switch to using npm ci after this issue gets closed: https://github.com/fsevents/fsevents/issues/301
        npm i
        npm run build --if-present
        npm test
      env:
        CI: true
